
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Micasita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ha14032023
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: